"""Adding street column

Revision ID: 7cda0b2d7d7c
Revises: 45153b1c2820
Create Date: 2024-02-11 17:12:44.629946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cda0b2d7d7c'
down_revision: Union[str, None] = '45153b1c2820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('street', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'street')
    # ### end Alembic commands ###
