"""Adding index column to the Addresses

Revision ID: 45153b1c2820
Revises: 12d45c4f7f2f
Create Date: 2024-02-11 17:05:52.226372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45153b1c2820'
down_revision: Union[str, None] = '12d45c4f7f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('index', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'index')
    # ### end Alembic commands ###
