"""tools for CRUD requests for order table

Revision ID: a978edf51ed7
Revises: 190bf95e9a68
Create Date: 2024-03-28 22:34:40.016678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a978edf51ed7'
down_revision: Union[str, None] = '190bf95e9a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('orders_customer_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['customer_id'], ['id'])
    op.drop_column('orders', 'customer')
    op.drop_column('orders', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('customer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_customer_fkey', 'orders', 'users', ['customer'], ['id'])
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
